# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c2107ae97a6f0378c5876b9871c74ad49af2272ebc90107e9ec2b9937b9d3e4907d2cf1d962b7f1e9047efd7ec0c2b9439f92d7f66cdd17643eb800c33517a03

test:
  secret_key_base: c50a37d385595834987170a2984dc19881623b0ed3f894d207947c37ea7ae148914c2a2ff44dd67d9b3a9f50906a014001abd3e1089db84f13abb1415327d616

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
